servers:
  server_docker0:
    host: 172.17.0.4
    port: 5038
    user: zabbix
    secret: 7ssJtwGG74n
    action: true

  server_read_only:
    host: 172.17.0.3
    port: 5038
    user: callsysuser
    secret: 12345
    action: false
collector:
  address: 0.0.0.0
  port: 5038
  user: collector
  secret: 12345

